name: CI

on: push

env:
  GOPATH: /home/runner/go
  GOBIN: /home/runner/go/bin
  GOPROXY: direct

jobs:
  test:
    runs-on: ubuntu-latest

    name: Go test
    steps:
      - uses: zendesk/checkout@v2
      - name: Setup Go
        uses: zendesk/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Test
        run: go test .
        